pre-commit:
  commands:
    notebooktester:
      priority: 1
      glob: '*.ipynb'
      run: notebooktester notebooks -v -t 240
    clean-jupyter:
      priority: 2
      files: git ls-files
      glob: '*.ipynb'
      run: jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    format:
      priority: 2
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: ruff format {staged_files}
      stage_fixed: true
    ruff:
      priority: 2
      files: git ls-files
      glob: '*.py'
      run: ruff check {staged_files} --fix
    typecheck:
      priority: 2
      files: git ls-files
      glob: '*.py'
      run: ty check {staged_files}
